variables:
    SolutionBaseName: 'DFC.Logger.AppInsights'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.9.0
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:
  - job: BuildTestAndAnalyze
    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: 'any cpu'
        BuildConfiguration: 'release'

    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-nuget-pack.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        DotNetCoreVersion: 3.1.101

- stage: PublishPackage
  displayName: Publish Package to NuGet
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: PublishNugetPackage
    environment: DFCApp_NUGET
    strategy:
      runOnce:
        deploy:
          steps:
          - task: NuGetCommand@2
            displayName: 'NuGet push'
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)\$(SolutionBaseName).Nuget\*.nupkg;!$(Pipeline.Workspace)\$(SolutionBaseName).Nuget\*.symbols.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: 'DFC Nuget'